### ISSUE TITLE
why is it similar to playx?

### ISSUE THREAD

**Issue by sthpravin** [roshancode/layx#1]

**Comment by roshanlam** [comment]
It's a clone of playx, in playx you can't play music from spotify but in layx you should be able to.

**Comment by deepjyoti30** [comment]
@roshanlam Whatever you want to do, this is not the proper way to do it. You've just copied our code and made it yours.
@NISH1001 and I have worked numerous hours to make playx what it is today. Don't just try to copy our code like this or we will be forced to take legal actions.

**Comment by NISH1001** [comment]
@roshanlam If you want to create or add new features, please fork the original repo and work on it.
Just stop doing copy-pasting everything. That's now how open-source works.
In fact, past few days I have been keeping an eye on your activities on this. You haven't complied with the license. 

If this goes on, we will make sure to take your repo down seriously. Stop copy-pasting and start doing open-source "thing" properly.


Here's something you might want to read:
https://opensource.guide/how-to-contribute/

@roshanlam  So, I request you, in all seriousness, humbly that you stop doing things in your claimed "layx" and fork "playx" and start complying with our license.
